name: Release

on:
  workflow_dispatch:   # manual “Run workflow”

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1 ▸ Checkout the branch you chose in the UI (default = main)
      - uses: actions/checkout@v4

      # 2 ▸ Ensure the latest CI on this branch passed
      - name: Check CI status
        run: |
          CI_STATUS=$(gh run list \
            --workflow=ci.yml \
            --branch=${{ github.ref_name }} \
            --limit=1 \
            --json conclusion \
            --jq '.[0].conclusion')

          if [[ "$CI_STATUS" != "success" ]]; then
            echo "❌ CI must pass before releasing. Current status: $CI_STATUS"
            exit 1
          fi
          echo "✅ CI passed. Proceeding with release…"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3 ▸ Calculate tags / CHANGELOG with release-please
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json      # your config
          manifest-file: .release-please-manifest.json  # version manifest

      # 4 ▸ Only continue if at least one package was released
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created == 'true' }}
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      # 5 ▸ Publish each released workspace package
      - name: Publish packages
        if: ${{ steps.release.outputs.release_created == 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "ℹ️  Packages flagged for publish:"
          echo "• core → ${{ steps.release.outputs['packages/core--release_version'] }}"
          echo "• cli  → ${{ steps.release.outputs['packages/cli--release_version'] }}"

          if [[ '${{ steps.release.outputs['packages/core--release_created'] }}' == 'true' ]]; then
            echo "📦 Publishing @react-zero-ui/core…"
            cd packages/core
            npm publish --access public
            cd ../..
          fi

          if [[ '${{ steps.release.outputs['packages/cli--release_created'] }}' == 'true' ]]; then
            echo "📦 Publishing create-zero-ui…"
            cd packages/cli
            npm publish --access public
            cd ../..
          fi
